<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SB.Solicitudes.Domain\SB.Solicitudes.Domain.csproj" />
    <ProjectReference Include="..\SB.Solicitudes.Presentation\SB.Solicitudes.Application.csproj" />
  </ItemGroup>

</Project>
